# Run locally with `act`:
#  > act -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:pwsh-latest

name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: pwsh
        run: |
          Invoke-Pester ./tests/* -CI -Output Detailed -Passthru
